/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

/**
 *
 * @author SadiaAlam
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Cal
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jPI = new javax.swing.JButton();
        jE = new javax.swing.JButton();
        jAns = new javax.swing.JButton();
        jSin = new javax.swing.JButton();
        jCos = new javax.swing.JButton();
        jTan = new javax.swing.JButton();
        jX10 = new javax.swing.JButton();
        jPow = new javax.swing.JButton();
        jRoot = new javax.swing.JButton();
        jLog = new javax.swing.JButton();
        jLn = new javax.swing.JButton();
        jFactorial = new javax.swing.JButton();
        jLeft = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jDot = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        jRight = new javax.swing.JButton();
        jPersentage = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        jEqual = new javax.swing.JButton();
        jAllClear = new javax.swing.JButton();
        jDivide = new javax.swing.JButton();
        jMulti = new javax.swing.JButton();
        jSubstct = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField.setEditable(false);
        jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jPI.setBackground(new java.awt.Color(111, 104, 104));
        jPI.setText("π");
        jPI.setPreferredSize(new java.awt.Dimension(54, 29));
        jPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPIActionPerformed(evt);
            }
        });

        jE.setBackground(new java.awt.Color(111, 104, 104));
        jE.setText("e");
        jE.setPreferredSize(new java.awt.Dimension(54, 29));
        jE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEActionPerformed(evt);
            }
        });

        jAns.setBackground(new java.awt.Color(111, 104, 104));
        jAns.setText("Ans");
        jAns.setPreferredSize(new java.awt.Dimension(54, 29));
        jAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnsActionPerformed(evt);
            }
        });

        jSin.setBackground(new java.awt.Color(111, 104, 104));
        jSin.setText("sin");
        jSin.setPreferredSize(new java.awt.Dimension(54, 29));
        jSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSinActionPerformed(evt);
            }
        });

        jCos.setBackground(new java.awt.Color(111, 104, 104));
        jCos.setText("cos");
        jCos.setPreferredSize(new java.awt.Dimension(54, 29));
        jCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCosActionPerformed(evt);
            }
        });

        jTan.setBackground(new java.awt.Color(111, 104, 104));
        jTan.setText("tan");
        jTan.setPreferredSize(new java.awt.Dimension(54, 29));
        jTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTanActionPerformed(evt);
            }
        });

        jX10.setBackground(new java.awt.Color(111, 104, 104));
        jX10.setText("<html>\nx10<sup><b>x</b></sup>\n</html>\n\n");
        jX10.setPreferredSize(new java.awt.Dimension(54, 29));
        jX10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jX10ActionPerformed(evt);
            }
        });

        jPow.setBackground(new java.awt.Color(111, 104, 104));
        jPow.setText("<html>\nX<sup>y</sup>\n</html>\n\n");
        jPow.setToolTipText("");
        jPow.setPreferredSize(new java.awt.Dimension(54, 29));
        jPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowActionPerformed(evt);
            }
        });

        jRoot.setBackground(new java.awt.Color(111, 104, 104));
        jRoot.setText("√");
        jRoot.setPreferredSize(new java.awt.Dimension(54, 29));
        jRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRootActionPerformed(evt);
            }
        });

        jLog.setBackground(new java.awt.Color(111, 104, 104));
        jLog.setText("log");
        jLog.setPreferredSize(new java.awt.Dimension(54, 29));
        jLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogActionPerformed(evt);
            }
        });

        jLn.setBackground(new java.awt.Color(111, 104, 104));
        jLn.setText("ln");
        jLn.setPreferredSize(new java.awt.Dimension(54, 29));
        jLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnActionPerformed(evt);
            }
        });

        jFactorial.setBackground(new java.awt.Color(111, 104, 104));
        jFactorial.setText("X!");
        jFactorial.setPreferredSize(new java.awt.Dimension(54, 29));
        jFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFactorialActionPerformed(evt);
            }
        });

        jLeft.setForeground(new java.awt.Color(126, 100, 100));
        jLeft.setText("(");
        jLeft.setPreferredSize(new java.awt.Dimension(54, 29));

        j7.setForeground(new java.awt.Color(126, 100, 100));
        j7.setText("7");
        j7.setPreferredSize(new java.awt.Dimension(54, 29));
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j4.setForeground(new java.awt.Color(126, 100, 100));
        j4.setText("4");
        j4.setPreferredSize(new java.awt.Dimension(54, 29));
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j1.setForeground(new java.awt.Color(126, 100, 100));
        j1.setText("1");
        j1.setPreferredSize(new java.awt.Dimension(54, 29));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j0.setForeground(new java.awt.Color(126, 100, 100));
        j0.setText("0");
        j0.setPreferredSize(new java.awt.Dimension(54, 29));
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ActionPerformed(evt);
            }
        });

        jDot.setForeground(new java.awt.Color(126, 100, 100));
        jDot.setText(".");
        jDot.setPreferredSize(new java.awt.Dimension(54, 29));
        jDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDotActionPerformed(evt);
            }
        });

        j2.setForeground(new java.awt.Color(126, 100, 100));
        j2.setText("2");
        j2.setPreferredSize(new java.awt.Dimension(54, 29));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j5.setForeground(new java.awt.Color(126, 100, 100));
        j5.setText("5");
        j5.setPreferredSize(new java.awt.Dimension(54, 29));
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j8.setForeground(new java.awt.Color(126, 100, 100));
        j8.setText("8");
        j8.setPreferredSize(new java.awt.Dimension(54, 29));
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        jRight.setForeground(new java.awt.Color(126, 100, 100));
        jRight.setText(")");
        jRight.setPreferredSize(new java.awt.Dimension(54, 29));

        jPersentage.setForeground(new java.awt.Color(126, 100, 100));
        jPersentage.setText("%");
        jPersentage.setPreferredSize(new java.awt.Dimension(54, 29));
        jPersentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersentageActionPerformed(evt);
            }
        });

        j9.setForeground(new java.awt.Color(126, 100, 100));
        j9.setText("9");
        j9.setPreferredSize(new java.awt.Dimension(54, 29));
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j6.setForeground(new java.awt.Color(126, 100, 100));
        j6.setText("6");
        j6.setPreferredSize(new java.awt.Dimension(54, 29));
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j3.setForeground(new java.awt.Color(126, 100, 100));
        j3.setText("3");
        j3.setPreferredSize(new java.awt.Dimension(54, 29));
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        jEqual.setForeground(new java.awt.Color(126, 100, 100));
        jEqual.setText("=");
        jEqual.setPreferredSize(new java.awt.Dimension(54, 29));
        jEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEqualActionPerformed(evt);
            }
        });

        jAllClear.setForeground(new java.awt.Color(126, 100, 100));
        jAllClear.setText("AC");
        jAllClear.setPreferredSize(new java.awt.Dimension(54, 29));
        jAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAllClearActionPerformed(evt);
            }
        });

        jDivide.setForeground(new java.awt.Color(126, 100, 100));
        jDivide.setText("/");
        jDivide.setPreferredSize(new java.awt.Dimension(54, 29));
        jDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivideActionPerformed(evt);
            }
        });

        jMulti.setForeground(new java.awt.Color(126, 100, 100));
        jMulti.setText("*");
        jMulti.setPreferredSize(new java.awt.Dimension(54, 29));
        jMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiActionPerformed(evt);
            }
        });

        jSubstct.setForeground(new java.awt.Color(126, 100, 100));
        jSubstct.setText("-");
        jSubstct.setPreferredSize(new java.awt.Dimension(54, 29));
        jSubstct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubstctActionPerformed(evt);
            }
        });

        jAdd.setForeground(new java.awt.Color(126, 100, 100));
        jAdd.setText("+");
        jAdd.setPreferredSize(new java.awt.Dimension(54, 29));
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rad", "Deg" }));
        jBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubstct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jX10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPersentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jX10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPersentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSubstct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //variables for all operations
    double firstNumber  = 0;
    double secondNumber  = 0;
    String operator;
    Object answer = 0;
    String r = "RAD";
    String show;
    
    
    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAllClearActionPerformed
        // TODO add your handling code here:
        jTextField.setText("");
            firstNumber  = 0;
            secondNumber  = 0;
            //result = 0;
    }//GEN-LAST:event_jAllClearActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
      
           /* String x = jTextField.getText() + j1.getText();
            jTextField.setText(x);*/
         String s= jTextField.getText();
        s=s+"1";
        jTextField.setText(s);                 


    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        
          String s= jTextField.getText();
        s=s+"2";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
   
        String s= jTextField.getText();
        s=s+"3";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        
          String s= jTextField.getText();
        s=s+"4";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
       
          String s= jTextField.getText();
        s=s+"5";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        
          String s= jTextField.getText();
        s=s+"6";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
       
          String s= jTextField.getText();
        s=s+"7";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
       
          String s= jTextField.getText();
        s=s+"8";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
         
         String s= jTextField.getText();
        s=s+"9";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j9ActionPerformed

    private void j0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ActionPerformed
        // TODO add your handling code here:
        
          String s= jTextField.getText();
        s=s+"0";
        jTextField.setText(s);                 

    }//GEN-LAST:event_j0ActionPerformed

    private void jDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDotActionPerformed
        // TODO add your handling code here:
        String x = jTextField.getText() + jDot.getText();
        jTextField.setText(x);
    }//GEN-LAST:event_jDotActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
         firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "+";
        
    }//GEN-LAST:event_jAddActionPerformed

    private void jEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEqualActionPerformed
        // TODO add your handling code here:
       
            
            switch (operator){
            case "+":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = firstNumber + secondNumber;
            
            show = firstNumber +" "+operator+" "+secondNumber;
                    break;
            case "-":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = firstNumber - secondNumber;
                    show = firstNumber +" "+operator+" "+secondNumber;
                    break;
            case "*":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = firstNumber * secondNumber;
                    show = firstNumber +" "+operator+" "+secondNumber;
                    break;
            case "/":secondNumber=Double.parseDouble(jTextField.getText());
                    
                    answer = (secondNumber==0)?"Undifined":firstNumber / secondNumber;
                    show = firstNumber +" "+operator+" "+secondNumber;
                    break;
            case "%":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = firstNumber*(secondNumber/100);
                    show = firstNumber +" "+operator+" "+secondNumber;
                    break;
            case "!":show = firstNumber +""+operator;
                    break;
            case "√":show = operator+"("+firstNumber +")";
                    break;
            case "log":show = operator+"("+firstNumber +")";
                    break;
            case "ln":show = operator+"("+firstNumber +")";
                    break;
            case "PI":show = firstNumber +"* π";
                    answer = (firstNumber==0)?3.1415926:firstNumber*3.1415926;
                    break;
            case "E":show = firstNumber + "* e";
                    answer = (firstNumber==0)?2.718282:firstNumber*2.718282;
                    break;
            case "sin":show = "sin("+firstNumber + ")";                    
                    break;
            case "cos":show = "cos("+firstNumber + ")";                    
                    break;
            case "tan":show = "tan("+firstNumber + ")";                    
                    break;
            case "x10":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = firstNumber * Math.pow(10, secondNumber);
                    show = firstNumber +"*10^"+secondNumber;
                    break;
            case "pow":secondNumber=Double.parseDouble(jTextField.getText());
                    answer = Math.pow(firstNumber, secondNumber);
                    show = firstNumber +"^"+secondNumber;
                    break;
            }
            
            jTextField.setText(""+answer);
        
        
        
        
    }//GEN-LAST:event_jEqualActionPerformed

    private void jSubstctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubstctActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "-";
        
         
    }//GEN-LAST:event_jSubstctActionPerformed

    private void jMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "*";
         
    }//GEN-LAST:event_jMultiActionPerformed

    private void jDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivideActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "/";
        
    }//GEN-LAST:event_jDivideActionPerformed

    private void jPersentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersentageActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "%";
        
    }//GEN-LAST:event_jPersentageActionPerformed

    private void jRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRootActionPerformed
        // TODO add your handling code here:
        operator = "√";
        
        String s = jTextField.getText();
        jTextField.setText("√("+s+")");
        firstNumber = Double.parseDouble(s);
        answer = Math.sqrt(firstNumber);
    }//GEN-LAST:event_jRootActionPerformed

    private void jFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFactorialActionPerformed
        // TODO add your handling code here:
        String s = jTextField.getText();
        jTextField.setText(s+"!");
        operator = "!";
       
        firstNumber = Double.parseDouble(s);
        double mTotal=1;
        for(int x=1; x<=firstNumber;x++)mTotal = mTotal * x;
        answer = mTotal; 
    }//GEN-LAST:event_jFactorialActionPerformed

    private void jLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogActionPerformed
        // TODO add your handling code here:
        String s = jTextField.getText();
        jTextField.setText("log("+s+")");
        operator = "log";
        
        firstNumber = Double.parseDouble(s);
        answer = Math.log10(firstNumber); 
        
    }//GEN-LAST:event_jLogActionPerformed

    private void jPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPIActionPerformed
        // TODO add your handling code here:
        String s = jTextField.getText();
        System.out.println(s);
        firstNumber = (s.equals(""))?0:Double.parseDouble(s);
        String k = (s.equals(""))?"":"*";
        jTextField.setText(s+k+"3.1415926");
        operator = "PI";
        
    }//GEN-LAST:event_jPIActionPerformed

    private void jEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEActionPerformed
        // TODO add your handling code here:
        String s = jTextField.getText();
        System.out.println(s);
        firstNumber = (s.equals(""))?0:Double.parseDouble(s);
        String k = (s.equals(""))?"":"*";
        jTextField.setText(s+k+"2.718282");
        operator = "PI";

    }//GEN-LAST:event_jEActionPerformed

    private void jAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnsActionPerformed
        // TODO add your handling code here:
        jTextField.setText(""+answer);
    }//GEN-LAST:event_jAnsActionPerformed

    private void jBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxActionPerformed
        // TODO add your handling code here:
        Object p = jBox.getSelectedItem();
        r= ""+p;
        System.out.println(r);
    }//GEN-LAST:event_jBoxActionPerformed

    private void jSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSinActionPerformed
        // TODO add your handling code here:
        operator = "sin";
        
        String p = jTextField.getText();
        jTextField.setText("sin("+p+")");
        firstNumber = (p.equals(""))?0:Double.parseDouble(p);
        answer = (r.equals("RAD"))?Math.sin(firstNumber):Math.sin(Math.toRadians(firstNumber));
        
    }//GEN-LAST:event_jSinActionPerformed

    private void jCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCosActionPerformed
        // TODO add your handling code here:
        operator = "cos";
       
        String p = jTextField.getText();
        jTextField.setText("cos("+p+")");
        firstNumber = (p.equals(""))?0:Double.parseDouble(p);
        answer = (r.equals("RAD"))?Math.cos(firstNumber):Math.cos(Math.toRadians(firstNumber));
    }//GEN-LAST:event_jCosActionPerformed

    private void jTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTanActionPerformed
        // TODO add your handling code here:
        operator = "tan";
        
        String p = jTextField.getText();
        jTextField.setText("tan("+p+")");
        firstNumber = (p.equals(""))?0:Double.parseDouble(p);
        answer = (r.equals("RAD"))?Math.tan(firstNumber):Math.tan(Math.toRadians(firstNumber));
    }//GEN-LAST:event_jTanActionPerformed

    private void jLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnActionPerformed
        // TODO add your handling code here:
        String s = jTextField.getText();
        jTextField.setText("log("+s+")");
        operator = "ln";
       
        firstNumber = Double.parseDouble(s);
        answer = Math.log(firstNumber); 
    }//GEN-LAST:event_jLnActionPerformed

    private void jX10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jX10ActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "x10";
         
    }//GEN-LAST:event_jX10ActionPerformed

    private void jPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jTextField.getText());
         jTextField.setText("");
         operator = "pow";
        
    }//GEN-LAST:event_jPowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jAllClear;
    private javax.swing.JButton jAns;
    private javax.swing.JComboBox<String> jBox;
    private javax.swing.JButton jCos;
    private javax.swing.JButton jDivide;
    private javax.swing.JButton jDot;
    private javax.swing.JButton jE;
    private javax.swing.JButton jEqual;
    private javax.swing.JButton jFactorial;
    private javax.swing.JButton jLeft;
    private javax.swing.JButton jLn;
    private javax.swing.JButton jLog;
    private javax.swing.JButton jMulti;
    private javax.swing.JButton jPI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPersentage;
    private javax.swing.JButton jPow;
    private javax.swing.JButton jRight;
    private javax.swing.JButton jRoot;
    private javax.swing.JButton jSin;
    private javax.swing.JButton jSubstct;
    private javax.swing.JButton jTan;
    private javax.swing.JTextField jTextField;
    private javax.swing.JButton jX10;
    // End of variables declaration//GEN-END:variables
}
